#!/bin/sh
#
# Wrapper script for reboot-dialog.pl incase it gets ran by root via
# apt-queue process.
#

# XAuthority may already exists, but force rediscovering the user's
# specific version. This prevents a race condition with gksudo if it
# happens to die before apt-queue has run us.
for X in /home/*/.Xauthority; do
    export XAUTHORITY=$X
    break
done

if [ "x$DISPLAY" = "x" ]; then
    # FIXME: Do this properly!
    export DISPLAY=:0.0
fi

env

echo "Calling Perl"
/usr/lib/jolicloud-notifier/reboot-dialog.pl $@ 2>&1
echo "done: $?"
