#!/bin/sh
#
# Wrapper script for reboot-dialog.pl incase it gets ran by root via
# apt-queue or dpkg process.
#

# XAuthority may already exists, but force rediscovering the user's
# specific version. This prevents a race condition with gksudo if it
# happens to die before apt-queue has run us.
for X in /home/*/.Xauthority; do
    export XAUTHORITY=$X
    break
done

if [ "x$DISPLAY" = "x" ]; then
    # FIXME: Do this properly!
    export DISPLAY=:0.0
fi

env

# If apt-queue is running in tandem, but did not trigger the
# update-notification itself, jolicloud-notifier must wait until apt-queue
# is finished before displaying the popup to reboot.
while pgrep apt-queue > /dev/null; do
    sleep 1;
done

echo "Calling Perl"
/usr/lib/jolicloud-notifier/reboot-dialog.pl $@ 2>&1
echo "done: $?"
