#!/bin/sh
#
# Wrapper script for reboot-dialog.pl incase it gets ran by root via
# apt-queue process.
#

if [ "x$XAUTHORITY" = "x" ]; then
    for X in /home/*/.Xauthority; do
        export XAUTHORITY=$X
        break
    done
fi

if [ "x$DISPLAY" = "x" ]; then
    # FIXME: Do this properly!
    export DISPLAY=:0.0
fi

env

/usr/lib/jolicloud-notifier/reboot-dialog.pl $@
