#!/bin/bash

set -e

case "$1" in
    configure)
        if dpkg --compare-versions "$2" le "1.1.2"; then
            echo "* Restoring update-notifiers's original update script"
            dpkg-divert --rename --remove /usr/share/update-notifier/notify-reboot-required
        fi
    ;;
esac

exit 0
