#!/bin/bash

set -e

case "$1" in
    install|upgrade)
        if dpkg --compare-versions "$2" le "1.0.0"; then
            echo "* Diverting update-notifiers's original update script"
            dpkg-divert --add --package "jolicloud-notifier" --divert /usr/share/update-notifier/notify-reboot-required.diverted --rename /usr/share/update-notifier/notify-reboot-required
        fi
    ;;
esac

exit 0
